### ISSUE TITLE
页面跳转有一个小bug，已经解决

### ISSUE THREAD

**Issue by xiaocuicui1937** [1em0nsOft/LemonBubble4Android#1]
我在使用的时候发现了一个小的问题，举个实际的例子：登录 输入账号和密码点击登录按钮，然后弹出等待加载的动画调用的是这个方法showRoundProgress，登陆成功就把动画hide掉。在跳转到主界面的时候，里面也有逻辑请求网络需要再次展示加载数据的动画，测试几次之后都没有反应换调用成功或者失败的方法都没有反应；最终在源码的LemonBubbleView类中发现泡泡对象初始化一次之后将haveInit = true，这样在同一个activity中就是传入相同的context是没有问题的，但是在传入其他的context时候无法再次被初始化也就无法显示相应的效果，其实解决方法很简单就是在hide方法中加上这句代码haveInit = false，就能解决这个小bug----嗯这样表述的应该没啥问题 了

**Comment by LemonITCN** [comment]
@xiaocuicui1937   您好 您使用的是哪一个版本呢  是否您使用的是旧版本的呢 最新的版本是1.0.9，已经有判断了  context不一致的时候设置haveInit为false，您现在是否好用呢，谢谢反馈，感谢您的支持

**Comment by xiaocuicui1937** [comment]
我直接导入的library应该是旧版本，不过问题解决了，整体不错还有就是内容过长的话显示不全

**Comment by LemonITCN** [comment]
@xiaocuicui1937   这个已经有解决方案了  可以让长文本自适应  会在下一版本发布，谢谢您的支持

**Comment by xiaocuicui1937** [comment]
好的 客气了，同时也谢谢你回答我的问题

**Comment by LemonITCN** [comment]
感谢您的支持
